name: Compile Eaglercraft Desktop
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run the Java Compiler
      run: chmod +x ./gradlew && ./gradlew clean build

    - name: Isolate the Finished Game
      run: |
        mkdir Eaglercraft_Game
        # This hunts down only the compiled Java files and puts them in our clean folder
        find build/libs -type f -name "*.jar" -exec cp {} Eaglercraft_Game/ \;

    - name: Upload the Finished Game
      uses: actions/upload-artifact@v4
      with:
        name: Eaglercraft-Desktop-Version
        path: Eaglercraft_Game/