name: Compile Eaglercraft
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run the TeaVM Compiler
      run: chmod +x ./gradlew && ./gradlew build

    - name: Isolate the Finished Game
      run: |
        mkdir Eaglercraft_Game
        find . -type f -name "*.html" -exec cp {} Eaglercraft_Game/ \;
        find . -type f -name "*.wasm" -exec cp {} Eaglercraft_Game/ \;

    - name: Upload the Finished Game
      uses: actions/upload-artifact@v4
      with:
        name: My-Modded-Eaglercraft
        path: Eaglercraft_Game/